### ISSUE TITLE
[bug] rate my professor discrepancy

### ISSUE THREAD

**Issue by knightron0** [unkn-wn/boilerclasses#105]
wrong RMP data is getting pulled for some professors. for example [MGMT 310](https://boilerclasses.com/detail/MGMT31000FinancialManagement): [Nathaniel Feige](https://www.ratemyprofessors.com/search/professors/783?q=Nathaniel%20Feige) doesn't have a RMP page and we display some other prof's (Nathaniel Lifton) rating in the ratings tab

also, further UX improvement: remove hyperlinks from the instructor listing under the header:
<img width="560" alt="Screenshot 2024-07-06 at 10 34 06 AM" src="https://github.com/unkn-wn/boilerclasses/assets/37767310/54a2e253-2852-4767-8549-d3c6156b668a">
it'll look cleaner + if the prof's page does not exist, will be less misleading

**Comment by SohamJog** [comment]
From feedback: Just reporting a bug, specifically noticed when searching course CE22200. When a specific professor does not exist on RateMyProfessor, the code still pulls data if a professor shows up with a different name. Ex: Geoffrey Graff is teaching CE22200 for Fall '25, however Geoffrey Wawrzyniak is the professor that shows up and data is pulled for on boilerclasses.

**Comment by SohamJog** [comment]
Fixed in the branch temp. 
Tested:
Nathaniel Feige in MGMT 310
Geoffrey Graff in CE22200

**Comment by SohamJog** [comment]
Removed hyperlinks for professors. Issue should be good to be closed after merging `temp`
