### ISSUE TITLE
[bug] Reddit logo not visible on course page (default image shown)

### ISSUE THREAD

**Issue by youngjun-yoo16** [unkn-wn/boilerclasses#111]
<img width="549" alt="Screenshot 2024-08-21 at 1 53 16 PM" src="https://github.com/user-attachments/assets/2faf9fc5-76cf-45e3-b6ba-e82da7fe1eb6">

The Reddit logo on the course page is not displaying correctly. Instead of the Reddit logo, a default image is shown, which typically indicates that the image path is incorrect or the image file is missing.

**Steps to Reproduce**:

1. Navigate to the course page for any course.
2. Locate the section with the Reddit button.
3. Observe that the logo is not displayed correctly and a default image placeholder is shown instead.

**Additional Information**:
- Browser: Chrome Version 127.0.6533.120 (Official Build) (arm64)

**Comment by knightron0** [comment]
thank you so much! this should be fixed now by #112 :)
