### ISSUE TITLE
[bug] some classes do not appear

### ISSUE THREAD

**Issue by unkn-wn** [unkn-wn/boilerclasses#54]
CS407, HIST35000

**Comment by unkn-wn** [comment]
Issue is that we don't scrape the category of classes CS407 is in, which we'll probably do later. HIST350 isn't even a class... ?

**Comment by knightron0** [comment]
- engr 131/132 also do not show up because they're marked as "studio" on the catalog

**Comment by knightron0** [comment]
MA 35301 - Linear Algebra II does not show up either

**Comment by unkn-wn** [comment]
Art classes do not show up either, @knightron0 hurry up

**Comment by knightron0** [comment]
fixed in [7c1633c](https://github.com/unkn-wn/boilerclasses/commit/7c1633c35c91004aa64870d484d2a8211384c1c9)
